CREATE TABLE Likes (
	UserId int NOT NULL FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE,
	MovieId int NOT NULL FOREIGN KEY REFERENCES Movies(MovieId) ON DELETE CASCADE,
	PRIMARY KEY (UserId, MovieId)
);